COOPERATE_CFG = {
    "control": {
        "control_type": "P",
        "decimation": 4,
        "action_scale": 0.25,
        "hip_scale_reduction": 0.5,
        "stiffness": {"joint": 50.0, "Z": 5.0},
        "damping": {"joint": 1.0, "Z": 0.5},
    },
    "sim": {
        "dt": 0.005,
    },
    "env": {
        "num_observations": 73,
        "num_privileged_obs": 2,
        "num_observation_history": 30,
        "num_actions": 12,
        "observe_two_prev_actions": True,
        "observe_clock_inputs": True,
        "observe_vel": False,
        "observe_only_lin_vel": False,
        "observe_yaw": False,
        "observe_contact_states": False,
    },
    "commands": {
        "num_commands": 3,
        "pacing_offset": False,
    },
    "init_state": {
        "default_joint_angles": {
            "FL_hip_joint": 0.1,
            "FL_thigh_joint": 0.8,
            "FL_calf_joint": -1.5,
            "FR_hip_joint": -0.1,
            "FR_thigh_joint": 0.8,
            "FR_calf_joint": -1.5,
            "RL_hip_joint": 0.1,
            "RL_thigh_joint": 1.0,
            "RL_calf_joint": -1.5,
            "RR_hip_joint": -0.1,
            "RR_thigh_joint": 1.0,
            "RR_calf_joint": -1.5,
            "Z_Joint1": 0.0,
            "Z_Joint2": -1.57,
            "Z_Joint3": 1.57,
            "Z_Joint4": 0.0,
            "Z_Joint5": 0.0,
            "Z_Joint6": 0.0,
        },
    },
    "normalization": {
        "clip_actions": 10.0,
        "obs_scales": {
            "lin_vel": 2.0,
            "ang_vel": 0.25,
            "dof_pos": 1.0,
            "dof_vel": 0.05,
            "height_measurements": 5.0,
            "body_height_cmd": 2.0,
            "footswing_height_cmd": 0.15,
            "body_pitch_cmd": 0.3,
            "body_roll_cmd": 0.3,
            "stance_width_cmd": 1.0,
            "stance_length_cmd": 1.0,
            "aux_reward_cmd": 1.0,
        },
    },
    "terrain": {
        "measure_heights": False,
        "measured_points_x": [],
        "measured_points_y": [],
    },
}
